"""Pull the Unity-free parts of real project files into compilable C#.

Some pure helpers live inside MonoBehaviours (Agent_EnvController) and some tests sit
beside tests that need the editor (AssetDatabase, live agents). Rather than keep hand
copies that drift, this lifts them out of the real files on every run:

  - named static members of Agent_EnvController / Agent_MatchSetup -> gen/Helpers.g.cs
  - every test-class member of the listed test files that does not touch an
    engine-only API                                                -> gen/<Test>.g.cs

A member that cannot be lifted is SKIPPED AND LISTED, never silently dropped, so the
report always says what this check did not cover.
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
GEN = os.path.join(os.path.dirname(os.path.abspath(__file__)), "gen")

# Members lifted verbatim out of runtime classes that cannot compile here.
HELPERS = {
    "Assets/Scripts/Agents/Agent_EnvController.cs": (
        "Agent_EnvController",
        ["TEAM_SPACING_RADIUS", "ParseSquadPattern", "SquadForPitch", "SpacingPenalty"],
    ),
    "Assets/Scripts/Gameplay/Agent_MatchSetup.cs": ("Agent_MatchSetup", ["MAX_SQUAD"]),
}

# Test files to mine. Members mentioning any of these need a real editor or engine.
TESTS = ["Assets/Tests/EditMode/Agent_EditMode_TeamTraining.cs"]
ENGINE_ONLY = [
    "AssetDatabase", "Application.", "Agent_Soccer.", "Reward_Settings", "GameObject",
    "ScriptableObject", "Object.Destroy", "Resources.", "AddComponent",
]


def top_level_members(body):
    """Split a class body into top-level member chunks (attributes/comments included).

    Braces inside string and char literals are skipped, so interpolated strings such
    as $"{spot}" do not upset the depth count.
    """
    chunks, start, depth, i, n = [], 0, 0, 0, len(body)
    while i < n:
        c = body[i]
        if c == "/" and body.startswith("//", i):
            i = body.find("\n", i)
            i = n if i < 0 else i
            continue
        if c == "/" and body.startswith("/*", i):
            i = body.find("*/", i) + 2
            continue
        if c == '"':
            verbatim = i > 0 and body[i - 1] == "@"
            i += 1
            while i < n:
                if not verbatim and body[i] == "\\":
                    i += 2
                    continue
                if body[i] == '"':
                    if verbatim and body.startswith('""', i):
                        i += 2
                        continue
                    break
                i += 1
            i += 1
            continue
        if c == "'":
            i = body.find("'", i + 2 if body[i + 1] == "\\" else i + 1) + 1
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                # A member ends here unless an initializer continues it (`= { ... };`).
                j = i + 1
                while j < n and body[j] in " \t":
                    j += 1
                end = j + 1 if j < n and body[j] == ";" else i + 1
                chunks.append(body[start:end])
                start = end
                i = end
                continue
        elif c == ";" and depth == 0:
            chunks.append(body[start:i + 1])
            start = i + 1
        i += 1
    return [c for c in chunks if c.strip()]


def class_body(src, name):
    m = re.search(r"\bclass\s+" + re.escape(name) + r"\b[^{]*\{", src)
    if not m:
        sys.exit(f"extract: class {name} not found")
    depth, i = 1, m.end()
    for j in range(i, len(src)):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                return src[i:j]
    sys.exit(f"extract: class {name} is unbalanced")


def declared_name(chunk):
    # Strip comments and attributes, then take the identifier before ( = ; or {.
    code = re.sub(r"//[^\n]*", "", chunk)
    code = re.sub(r"^\s*\[[^\]]*\]\s*", "", code, flags=re.M)
    m = re.search(r"(\w+)\s*(\(|=|;|\{|=>)", code)
    return m.group(1) if m else None


def main():
    os.makedirs(GEN, exist_ok=True)
    skipped = []

    parts = ["// <auto-generated> by extract.py from the real sources. Do not edit.\n",
             "using UnityEngine;\n\nnamespace PoSoccer\n{\n"]
    for rel, (cls, wanted) in HELPERS.items():
        src = open(os.path.join(ROOT, rel), encoding="utf-8-sig").read()
        found = {declared_name(c): c for c in top_level_members(class_body(src, cls))}
        parts.append(f"    public static partial class {cls}\n    {{\n")
        for name in wanted:
            if name not in found:
                sys.exit(f"extract: {cls}.{name} not found in {rel} - was it renamed?")
            parts.append(found[name].rstrip() + "\n")
        parts.append("    }\n")
    parts.append("}\n")
    open(os.path.join(GEN, "Helpers.g.cs"), "w").write("".join(parts))

    for rel in TESTS:
        src = open(os.path.join(ROOT, rel), encoding="utf-8-sig").read()
        cls = re.search(r"\bclass\s+(\w+)", src).group(1)
        kept = []
        for chunk in top_level_members(class_body(src, cls)):
            hit = next((t for t in ENGINE_ONLY if t in chunk), None)
            if hit:
                skipped.append(f"{cls}.{declared_name(chunk)} (uses {hit.rstrip('.')})")
            else:
                kept.append(chunk)
        out = ("// <auto-generated> by extract.py from " + rel + ". Do not edit.\n"
               "using System;\nusing NUnit.Framework;\nusing UnityEngine;\n\n"
               "namespace PoSoccer.Tests\n{\n"
               f"    public sealed class {cls}\n    {{\n" + "".join(kept).rstrip() + "\n    }\n}\n")
        open(os.path.join(GEN, cls + ".g.cs"), "w").write(out)

    if skipped:
        print("NOT COVERED here (needs the Unity editor):")
        for s in skipped:
            print("  - " + s)


if __name__ == "__main__":
    main()
