# Generates one trainer config per personality for the rescaled pitch.
# The curriculum's completion_criteria.behavior must name a single behavior, so
# the four brains cannot share one file - they are generated from one template
# instead, which keeps the hyperparameters identical by construction.
param([int]$MaxSteps = 10000000)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$profiles = @("STANDARD", "MATT", "KIM", "NICK")

foreach ($name in $profiles) {
    $yaml = @"
# Auto-generated by scripts/write-configs-v2.ps1 - do not hand-edit.
# v2: rescaled pitch (36 x 54 m playable), 4-action space
# (forward/lateral/turn/boost), traction-limited locomotion.
behaviors:
  ${name}:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: ${MaxSteps}
    time_horizon: 1024
    summary_freq: 20000
    checkpoint_interval: 250000
    keep_checkpoints: 5
    threaded: false

environment_parameters:
  goal_width:
    curriculum:
      # Thresholds are deliberately lower than v1: the 20M-step run never left
      # Lesson0 at threshold 0.35, which meant the curriculum was inert.
      - name: Lesson0_WideNet
        completion_criteria:
          measure: reward
          behavior: ${name}
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.15
        value: 18.0
      - name: Lesson1_MidNet
        completion_criteria:
          measure: reward
          behavior: ${name}
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.35
        value: 12.0
      # Regulation goal width on the rescaled pitch.
      - name: Lesson2_Regulation
        value: 7.32

env_settings:
  num_envs: 1

engine_settings:
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
"@
    $path = Join-Path $root "config\TRAIN_${name}_v2.yaml"
    Set-Content -Path $path -Value $yaml -NoNewline
    Write-Host "wrote config/TRAIN_${name}_v2.yaml"
}
